version: '3.1'
services:
  app:
    container_name: thc
    image: thc
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - sql-server-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://192.168.144.231/thc
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Root@123

  sql-server-db:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    container_name: sql-server-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Root@123"
      ACCEPT_EULA: "Y"